# Generated by Django 3.1.3 on 2020-11-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followers_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user_id', models.IntegerField()),
                ('follower_user_id', models.IntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tweet_body', models.CharField(max_length=140)),
                ('retweet_count', models.IntegerField()),
                ('likes_count', models.IntegerField()),
                ('replies_count', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('published_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
